openapi: 3.0.0
info:
  title: PARKING MANAGEMENT SYSTEM
  description: MongoDB ExpressJS NodeJS REST API
  version: 1.0.0
servers:
  - url: http://localhost:4000/api/
    description: Localhost development server 
  
components:
  securitySchemes:
    ApiKeyAuth:        # arbitrary name for the security scheme
      type: apiKey
      in: header       # can be "header", "query" or "cookie"
      name: auth-token

  schemas:
    Parking:
      type: object
      properties:
        id:
          type: string
        vehicleNumber:
          type: string
        parkingSlot:
          type: string
        entryTime:
          type: string
        exitTime:
          type: string
        date:
          type: string
        fare:
          type: number
        parkingAlloted:
          type: number    
    
    User:
      type: object
      properties:
        name:
            type: string
        email:
          type: string
        password:
          type: string
        date:
          type: string

paths:

  /user/register:
    post:
      summary: Register a new User
      description: Register a new User in the database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"

      responses:
        201:
          description: User created succesfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  _id:
                    type: string

  /user/login:
    post:
      summary: Login a User
      description: Login a User in order to get JWT token (auth-token)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      
      responses:
        200:
          description: User logged in succesfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  data:
                    type: string


  /parking:
    get:
      summary: Retrieves a list of parkings
      description: Retrieves the list of parkings as JSON objects.
      responses:
        200:
          description: The list of parking JSON objects in an array.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Parking"
    
    post:
      summary: Create a new Parking
      description: Create a new Parking
      security:
        - ApiKeyAuth: []      
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Parking"

      responses:
        201:
          description: Parking created succesfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Parking"
  /parking/parkingAlloted:
    get:
      summary: Specific Parking
      description: Retrieves a specific Parking based on allotted
      parameters:
        - in: path
          name: parkingAlloted
          schema:
            type: boolean
            
      responses:
        200:
          description: Parking in the format of a JSON object.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Parking"

  
  /parking/{id}:
    get:
      summary: Specific Parking
      description: Retrieves a specific Parking based on it id.
      parameters:
        - in: path
          name: id
          required: true
          description: MongoDB id
          schema:
            type: string
            
      responses:
        200:
          description: Parking in the format of a JSON object.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Parking"
  
  
   
    put:
      summary: Updates a specific Parking
      description: Updates a specific Parking based on it id
      security:
        - ApiKeyAuth: []            
      parameters:
        - in: path
          name: id
          required: true
          description: MongoDB id
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Parking"

      responses:
        201:
          description: Parking updated succesfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Parking"

    delete:
      summary: Deletes a specific Parking slot
      description: Deletes a specific Parking based on it id
      security:
        - ApiKeyAuth: []            
      parameters:
        - in: path
          name: id
          required: true
          description: MongoDB id
          schema:
            type: string      

      responses:
        201:
          description: Parking deleted succesfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Parking"

  


    

    
